// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
    

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCmu7WKBtwPy77DYvw8F5_ejIvGhmG9UA',
    appId: '1:368040626674:web:dbd7f9e0e57a01f07a036b',
    messagingSenderId: '368040626674',
    projectId: 'motordealgranada',
    authDomain: 'motordealgranada.firebaseapp.com',
    storageBucket: 'motordealgranada.firebasestorage.app',
    measurementId: 'G-849NHCRJFR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWL3xyEnzl9FBBb3xRBooZ_Wu-JxUsT-k',
    appId: '1:368040626674:android:d4368d1edb783cf37a036b',
    messagingSenderId: '368040626674',
    projectId: 'motordealgranada',
    storageBucket: 'motordealgranada.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv761dgP4UZYLufM76VGNRhkw9tiBW4ok',
    appId: '1:368040626674:ios:a64a5eefe59cb1337a036b',
    messagingSenderId: '368040626674',
    projectId: 'motordealgranada',
    storageBucket: 'motordealgranada.firebasestorage.app',
    iosBundleId: 'com.example.motorDealGranada',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCv761dgP4UZYLufM76VGNRhkw9tiBW4ok',
    appId: '1:368040626674:ios:a64a5eefe59cb1337a036b',
    messagingSenderId: '368040626674',
    projectId: 'motordealgranada',
    storageBucket: 'motordealgranada.firebasestorage.app',
    iosBundleId: 'com.example.motorDealGranada',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCmu7WKBtwPy77DYvw8F5_ejIvGhmG9UA',
    appId: '1:368040626674:web:ed8d8bb5a931caf67a036b',
    messagingSenderId: '368040626674',
    projectId: 'motordealgranada',
    authDomain: 'motordealgranada.firebaseapp.com',
    storageBucket: 'motordealgranada.firebasestorage.app',
    measurementId: 'G-6KJZC2QK4C',
  );
}
